# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
bio: 'Node.js archmage, borderline insane but still packing a punch.'

# Content
excerpt_link: Read More

# LESS include paths
less:
  paths:
    - source/css/bundle.less

# Scripts to include
scripts:
  - jquery/dist/jquery.min.js
  - headroom.js/dist/headroom.min.js
  - headroom.js/dist/jQuery.headroom.min.js
